language: node_js

node_js:
  - 10

cache:
  directories:
    - node_modules

script:
  - npm run coverage
  - npm run build:docs

after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $github_token
    local_dir: build
    on:
      branch: master

  - provider: npm
    email: "andy@leftshoedevelopment.com"
    api_key: $npm_token
    on:
      tags: true
