language: node_js

node_js:
  - 10

cache:
  directories:
    - node_modules

script:
  - npm run coverage
  - npm run build:docs

after_script: # Upload coverage reports
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
